const mockData = {
  page: 1,
  results: [
    {
      title: "Deal",
      overview:
        "As an ex-gambler teaches a hot-shot college kid some things about playing cards, he finds himself pulled into the world series of poker, where his protégé is his toughest competition.",
      poster_path: "/zm1FN17vlQb3h5RdQfjPzNvDLWe.jpg",
      release_date: "2008-01-29",
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35, 18],
      id: 139929,
      original_language: "nl",
      original_title: "Deal",
      overview:
        "After a couple of drinks two twenty-something students make a deal to have sex with each other for 2000 Euros. The deal takes them to Barcelona. There, their mutual embarrassment over the deal complicates matters, but brings them closer together.",
      popularity: 0.638,
      poster_path: "/b0Cu4oO64IY28XfWLIsZwZB2MjC.jpg",
      release_date: "2012-09-28",
      title: "Deal",
      video: false,
      vote_average: 5,
      vote_count: 6,
    },
    {
      adult: false,
      backdrop_path: "/igBXcB9KkYis1sspNgqxWl9tRsJ.jpg",
      genre_ids: [18, 10749],
      id: 399905,
      original_language: "ko",
      original_title: "여자전쟁: 비열한 거래",
      overview:
        "Painter Ha-rim became blind due to an unfortunate accident. His wife Sun-yeong searches far and low for a cornea donor until she meets terminal cancer patient Dae-geun. These two make a startling and dangerous deal for Ha-rim's cornea.",
      popularity: 34.737,
      poster_path: "/2xUNRZwprvVwfx12WR1rRXoohSi.jpg",
      release_date: "2015-09-27",
      title: "Female War: A Nasty Deal",
      video: false,
      vote_average: 5.5,
      vote_count: 27,
    },
    {
      adult: false,
      backdrop_path: "/8tDr1OZhLPpDAvmFDHjLnrKLOQH.jpg",
      genre_ids: [18],
      id: 1062644,
      original_language: "fr",
      original_title: "La Promesse verte",
      overview:
        "Carole tries to save the life of her son who has been wrongfully sentenced to death in a rigged trial.",
      popularity: 7.235,
      poster_path: "/8gkvKdu3wYvNfkaRGap60iguZAX.jpg",
      release_date: "2024-03-27",
      title: "The Green Deal",
      video: false,
      vote_average: 6.756,
      vote_count: 45,
    },
    {
      adult: false,
      backdrop_path: "/ryoWP1kvNcwPif6uNbuZwQfrJPy.jpg",
      genre_ids: [35, 80],
      id: 24382,
      original_language: "it",
      original_title: "I soliti ignoti",
      overview:
        "Best friends Peppe and Mario are thieves, but they're not very good at it. Still, Peppe thinks that he's finally devised a master heist that will make them rich. With the help of some fellow criminals, he plans to dig a tunnel from a rented apartment to the pawnshop next door, where they can rob the safe. But his plan is far from foolproof, and the fact that no one in the group has any experience digging tunnels proves to be the least of their problems.",
      popularity: 12.293,
      poster_path: "/f5OxD8Nl0pR3DcYHtYhHRfpsmjl.jpg",
      release_date: "1958-07-26",
      title: "Big Deal on Madonna Street",
      video: false,
      vote_average: 8.1,
      vote_count: 700,
    },
    {
      adult: false,
      backdrop_path: "/4IAq8KJgjTBm70APzyAK9dx8UGu.jpg",
      genre_ids: [16, 12, 35, 10751],
      id: 518755,
      original_language: "ru",
      original_title: "Волки и овцы: Ход свиньёй",
      overview:
        "The united town of sheep and wolves lives a peaceful and quiet life until two unexpected guests turn up - a polar fox and a tiny ewe. No one ever expected them to bring a deadly danger, which can be overcome only if they work together. Only teamwork can solve big problems and deal with serious challenges - as there is strength in unity.",
      popularity: 7.415,
      poster_path: "/sVizGmUr06F8LrVXt6nEYrmwmos.jpg",
      release_date: "2019-01-24",
      title: "Sheep & Wolves: Pig Deal",
      video: false,
      vote_average: 6.6,
      vote_count: 80,
    },
    {
      adult: false,
      backdrop_path: "/mUc78NcZ3jikLyr1GMQQzx8PATd.jpg",
      genre_ids: [35],
      id: 1124624,
      original_language: "es",
      original_title: "Soltera codiciada 2",
      overview:
        "María Fe, still single but not so sought after, faces the existential crisis and the blank page as any mature and sensible woman would: by getting involved with the wrong guy.",
      popularity: 5.821,
      poster_path: "/6zaI5w6W8wG8WgqdVvdMJ2a7C9X.jpg",
      release_date: "2023-07-06",
      title: "How to Deal with a Heartbreak",
      video: false,
      vote_average: 7.143,
      vote_count: 35,
    },
    {
      adult: false,
      backdrop_path: "/hK3hsL2QLaIzwjEpgqB9ww5shUG.jpg",
      genre_ids: [35, 12, 28],
      id: 1204912,
      original_language: "fr",
      original_title: "Un stupéfiant Noël !",
      overview:
        "On Christmas Eve, Greg, a solitary and taciturn police officer, doesn't hesitate to leave his daughter behind to go on a mission. To teach him a lesson, Santa Claus decides to grant his daughter's wish: that her father looks like Richard Silestone, the good-natured and heavily indebted family man from the beloved Christmas movie she adores. While Greg is sent into this improbable world, Richard accidentally lands in the real world and both men realize they have no choice but to complete each other's missions to reclaim their respective lives.",
      popularity: 9.608,
      poster_path: "/9kKDdxX0KZ6x2F5FNCUOa4VQEji.jpg",
      release_date: "2023-12-07",
      title: "Dealing with Christmas",
      video: false,
      vote_average: 5.6,
      vote_count: 60,
    },
  ],
};
